# Generated by Django 4.2.3 on 2023-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
