# Generated by Django 4.2.3 on 2023-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_salary_job_max_salary_job_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.FloatField(null=True),
        ),
    ]
